<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="ur
	n:schemas-microsoft-com:office:office" xmlns:w="urn:schem
	as-microsoft-com:office:word" xmlns:m="http://schemas.mic
	rosoft.com/office/2004/12/omml" xmlns="http://www.w3.org/
	TR/REC-html40"><head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="Generato
	r" content="Microsoft Word 15 (filtered medium)"/>
	<!--[i
	f !mso]><style>v\:* {behavior:url(#default#VML);}
	o\:* {
	behavior:url(#default#VML);}
	w\:* {behavior:url(#default
	#VML);}
	.shape {behavior:url(#default#VML);}
	</style><!
	[endif]--><style><!--
	/* Font Definitions */
	@font-face
	
		{font-family:"Cambria Math";
		panose-1:2 4 5 3 5 4 6 
	3 2 4;}
	@font-face
		{font-family:Calibri;
		panose-1:2 
	15 5 2 2 2 4 3 2 4;}
	@font-face
		{font-family:"Apple Co
	lor Emoji";
		panose-1:0 0 0 0 0 0 0 0 0 0;}
	@font-face
	
		{font-family:Poppins;
		panose-1:0 0 5 0 0 0 0 0 0 0;}
	
	@font-face
		{font-family:"Source Sans Pro";
		panose-1:
	2 11 5 3 3 4 3 2 2 4;}
	@font-face
		{font-family:-apple-
	system;
		panose-1:2 11 6 4 2 2 2 2 2 4;}
	/* Style Defin
	itions */
	p.MsoNormal, li.MsoNormal, div.MsoNormal
		{ma
	rgin:0cm;
		text-align:right;
		direction:rtl;
		unicode-
	bidi:embed;
		font-size:10.0pt;
		font-family:"Calibri",s
	ans-serif;}
	a:link, span.MsoHyperlink
		{mso-style-prior
	ity:99;
		color:#0563C1;
		text-decoration:underline;}
	s
	pan.EmailStyle19
		{mso-style-type:personal-reply;
		font
	-family:"Calibri",sans-serif;
		color:windowtext;}
	.MsoC
	hpDefault
		{mso-style-type:export-only;
		font-size:10.0
	pt;
		mso-ligatures:none;}
	@page WordSection1
		{size:61
	2.0pt 792.0pt;
		margin:72.0pt 90.0pt 72.0pt 90.0pt;}
	di
	v.WordSection1
		{page:WordSection1;}
	--></style><!--[if
	 gte mso 9]><xml>
	<o:shapedefaults v:ext="edit" spidmax=
	"1026" />
	</xml><![endif]--><!--[if gte mso 9]><xml>
	<o
	:shapelayout v:ext="edit">
	<o:idmap v:ext="edit" data="1
	" />
	</o:shapelayout></xml><![endif]-->
	</head>
	<body lang="en-IL" link="#0563C1" vlink="#954F72" style="word-w
	rap:break-word">
	<div class="WordSection1">
	<p class="M
	soNormal" style="text-align:left;direction:ltr;unicode-bi
	di:embed"><span lang="EN-US" style="font-size:11.0pt">htt
	ps://youtube.com<o:p></o:p></span></p>
	<p class="MsoNorm
	al" style="text-align:left;direction:ltr;unicode-bidi:emb
	ed"><span style="font-size:11.0pt"><o:p> </o:p></span></p>
	<div id="mail-editor-reference-message-container">
	<div>
	<div style="border:none;border-top:solid #B5C4D
	F 1.0pt;padding:3.0pt 0cm 0cm 0cm">
	<p class="MsoNormal" style="margin-bottom:12.0pt;text-align:left;direction:lt
	r;unicode-bidi:embed">
	<b><span style="font-size:12.0pt;
	color:black">From: </span></b><span style="font-size:12.0
	pt;color:black">Yuri Khomyakov &lt;yurik@cynet.com&gt;<br/>
	<b>Date: </b>Monday, 9 October 2023 at 14:50<br/>
	<b>T
	o: </b>eyaltest@cynetint.onmicrosoft.com &lt;eyaltest@cyn
	etint.onmicrosoft.com&gt;<br/>
	<b>Subject: </b>FW: Hackma
	te 2023 - Yossi, David &amp; Emanuel<o:p></o:p></span></p>
	</div>
	<p class="MsoNormal" style="text-align:left;di
	rection:ltr;unicode-bidi:embed"><span style="font-size:11
	.0pt"> </span><o:p></o:p></p>
	<p class="MsoNormal" style="text-align:left;direction:ltr;unicode-bidi:embed">
	<span style="font-size:11.0pt"> </span><o:p></o:p><!--
	p-->
	</p><div id="mail-editor-reference-message-container">
	&lt;
	div&gt;
	<div style="border:none;border-top:solid #B5C4DF 1.
	0pt;padding:3.0pt 0cm 0cm 0cm">
	<p class="MsoNormal" sty="" le="margin-bottom:12.0pt;text-align:left;direction:ltr;un
	icode-bidi:embed">
	<b><span style="font-size:12.0pt;colo
	r:black">From: </span></b><span style="font-size:12.0pt;c
	olor:black">Yuri Khomyakov &lt;yurik@cynet.com&gt;<br/>
	&lt;
	b&gt;Date: Thursday, 5 October 2023 at 16:12<br/>
	<b>To:
	 </b>eyaltest@cynetint.onmicrosoft.com &lt;eyaltest@cynet
	int.onmicrosoft.com&gt;<br/>
	<b>Subject: </b>FW: Hackmate
	 2023 - Yossi, David &amp; Emanuel</span><o:p></o:p></p>
	
	</div>
	<p class="MsoNormal" style="text-align:left;dire
	ction:ltr;unicode-bidi:embed"><span style="font-size:11.0
	pt"> </span><o:p></o:p></p>
	<p class="MsoNormal" st="" yle="text-align:left;direction:ltr;unicode-bidi:embed"><s pan="" style="font-size:11.0pt"> <o:p></o:p></s></p><s pan="" style="font-size:11.0pt">
	
	<div id="mail-editor-reference-message-container">
	<di v="">
	<div style="border:none;border-top:solid #B5C4DF 1.0p
	t;padding:3.0pt 0cm 0cm 0cm">
	<p class="MsoNormal" style="margin-bottom:12.0pt;text-align:left;direction:ltr;unic
	ode-bidi:embed">
	<b><span lang="EN-US" style="font-size:
	12.0pt;color:black">From: </span></b><span lang="EN-US" s="" tyle="font-size:12.0pt;color:black">Hadar Sahar &lt;hadar
	s@cynet.com&gt;<br/>
	<b>Date: </b>Tuesday, 5 September 20
	23 at 12:49<br/>
	<b>To: </b>All &lt;all@cynet.com&gt;<br/>
	
	<b>Cc: </b>Gal Tandler &lt;galt@cynet.com&gt;, Aldema G
	ilad &lt;aldemag@cynet.com&gt;<br/>
	<b>Subject: </b>Hackm
	ate 2023 - Yossi, David &amp; Emanuel</span><o:p></o:p><!--
	p-->
	</p></div>
	<p class="MsoNormal" align="center" dir="RTL" style="text-align:center"><b><span lang="HE" style="font
	-size:22.0pt;color:#FF3399;mso-ligatures:standardcontextu
	al">ביום חמישי הקרוב זה קורה!
	</span></b><span dir="LTR"><o:p></o:p></span></p>
	<p class="Ms
	oNormal" align="center" dir="RTL" style="text-align:cente
	r"><b><u><span lang="HE" style="font-size:22.0pt;color:#F
	F3399;mso-ligatures:standardcontextual">יוסי, עמנ
	אל ודוד הולכים לייצג אותנו בטו
	ניר השחמט הארצי של חברות הסייב
	 המובילות בישראל!</span></u></b><span lang="HE"><o:p></o:p></span></p>
	<p class="MsoNormal" align="center" dir="RTL" style="text-align:center"><b><span lan="" g="HE" style="font-size:22.0pt;color:#FF3399;mso-ligature
	s:standardcontextual">כולנו מחזיקים אצבע
	ת ובטוחים שתייצגו אותנו בכבוד!&lt;
	/span&gt;</span></b><span lang="HE"><o:p></o:p></span></p>
	<p clas="" s="MsoNormal" align="center" dir="RTL" style="text-align:
	center"><b><span lang="HE" style="font-size:22.0pt;color:
	#FF3399;mso-ligatures:standardcontextual"> </span><!--
	b--><span lang="HE"><o:p></o:p></span></b></p><b>
	<p class="MsoNo
	rmal" align="center" dir="RTL" style="text-align:center">
	<b><span lang="HE" style="font-size:22.0pt;color:#FF3399;
	mso-ligatures:standardcontextual">מעוניינים לה
	גיע לעודד?
	</span></b><span lang="HE"><o:p></o:p></span></p>
	<p class="MsoNormal" align="center" dir="RT
	L" style="text-align:center"><b><span lang="HE" style="fo
	nt-size:22.0pt;color:#FF3399;mso-ligatures:standardcontex
	tual">עדכנו את צוות ה</span></b><b><span dir="LTR" style="font-size:22.0pt;color:#FF3399;mso-ligatures
	:standardcontextual">HR</span></b><span dir="RTL"></span>
	<span dir="RTL"></span><b><span lang="HE" style="font-siz
	e:22.0pt;color:#FF3399;mso-ligatures:standardcontextual">
	<span dir="RTL"></span><span dir="RTL"></span>
	 ונדא
	ג לכם לכניסה לטורניר </span></b><b><span dir="LTR" style="font-size:22.0pt;font-family:&#34;Appl
	e Color Emoji&#34;;color:#FF3399;mso-ligatures:standardc
	ontextual">😊</span></b><span lang="HE"><o:p></o:p></span></p>
	<p class="MsoNormal" align="center" dir="RT
	L" style="text-align:center"><span dir="LTR"></span><span dir="LTR"></span><b><span lang="EN-US" dir="LTR" style="
	font-size:22.0pt;mso-ligatures:standardcontextual"><span dir="LTR"></span><span dir="LTR"></span> </span></b>
	<span lang="HE"><o:p></o:p></span></p>
	<p class="MsoNorm
	al" align="center" dir="RTL" style="text-align:center"><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt"><img width="664" height="664" style="width:6.9166in;height:6.9
	166in" id="Picture_x0020_8" src="cid:image001.jpg@01D9DFF
	7.3742A150"/><span lang="HE"><o:p></o:p></span></s></p><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt">
	
	<p class="MsoNormal" dir="RTL"><span dir="LTR"></span>&lt;
	span dir=&#34;LTR&#34;&gt;<span lang="EN-US" dir="LTR" style="font-size:12.0pt;mso-ligatures:standardcontextual"><span dir="LTR"></span><span dir="LTR"></span> </span><sp an="" lang="HE"><o:p></o:p></sp></p>
	<table class="MsoNor
	malTable" border="0" cellpadding="0">
	<tbody>
	<tr>
	<td width="260" valign="bottom" style="width:195.0pt;padding
	:.75pt 33.75pt .75pt .75pt">
	<table class="MsoNormalTabl
	e" border="0" cellpadding="0">
	<tbody>
	<tr>
	<td style="padding:.75pt .75pt .75pt .75pt">
	<p class="MsoNormal" align="right" style="text-align:right;direction:ltr;unico
	de-bidi:embed">
	<span style="font-size:11.0pt"><img widt="" h="70" height="37" style="width:.7291in;height:.3854in" i="" d="Picture_x0020_1" src="cid:image002.png@01D9DFF7.3742A1
	50" alt="Crop"/></span><span lang="HE" dir="RTL"><o:p></o:p></span></p>
	</td>
	</tr>
	<tr>
	<td style="padding:.75
	pt .75pt .75pt .75pt">
	<p class="MsoNormal" align="cente
	r" style="text-align:center;direction:ltr;unicode-bidi:em
	bed">
	<span style="font-size:11.0pt"><img width="134" he="" ight="134" style="width:1.3958in;height:1.3958in" id="Pic
	ture_x0020_2" src="cid:image003.png@01D9DFF7.3742A150"/><!--
	span--><o:p></o:p></span></p>
	</td>
	</tr>
	<tr>
	<td style="padd
	ing:.75pt .75pt .75pt .75pt">
	<p class="MsoNormal" style="text-align:left;direction:ltr;unicode-bidi:embed"><span style="font-size:11.0pt"><img width="194" height="52" st="" yle="width:2.0208in;height:.5416in" id="Picture_x0020_3" src="cid:image004.png@01D9DFF7.3742A150" alt="Cloud"/><o:p></o:p></span></p>
	</td>
	</tr>
	</tbody>
	</table>
	
	</td><td style="padding:.75pt .75pt .75pt .75pt">
	<tbod y="">
	</tbod><table class="MsoNormalTable" border="0" cellpadding="0">
	<tbody><tr>
	<td colspan="5" style="padding:.75pt .75pt .75p
	t .75pt">
	<p class="MsoNormal" style="margin-bottom:2.25
	pt;text-align:left;direction:ltr;unicode-bidi:embed">
	<b><span style="font-size:18.0pt;font-family:Poppins;color:
	#1E202C">Hadar Sahar</span></b><o:p></o:p></p>
	</td>
	<!--
	tr-->
	</tr><tr>
	<td colspan="5" style="padding:.75pt .75pt .75
	pt .75pt">
	<p class="MsoNormal" style="text-align:left;l
	ine-height:15.0pt;direction:ltr;unicode-bidi:embed">
	<b>
	<span style="font-size:12.0pt;font-family:&#34;Source Sa
	ns Pro&#34;,sans-serif;color:#F9379F">Wellbeing Manager&lt;
	/span&gt;</span></b><o:p></o:p></p>
	</td>
	</tr>
	<tr>
	<td colspa="" n="5" style="padding:.75pt .75pt .75pt .75pt">
	<p class="MsoNormal" style="text-align:left;direction:ltr;unicode-
	bidi:embed"><span style="font-size:11.0pt"><img width="1" height="1" style="width:.0104in;height:.0104in" id="Pict
	ure_x0020_4" src="cid:image005.png@01D9DFF7.3742A150"/><o:p></o:p></span></p>
	</td>
	</tr>
	<tr>
	<td colspan="5" style="padding:.75pt .75pt .75pt .75pt">
	<p class="MsoNo
	rmal" style="text-align:left;direction:ltr;unicode-bidi:e
	mbed"><b><span style="font-size:10.5pt;font-family:&#34;
	Source Sans Pro&#34;,sans-serif;color:#1E202C">052-73644
	22</span></b><o:p></o:p></p>
	</td>
	</tr>
	<tr>
	<td col="" span="5" style="padding:.75pt .75pt .75pt .75pt">
	<p cla="" ss="MsoNormal" style="text-align:left;direction:ltr;unico
	de-bidi:embed"><span style="font-size:11.0pt;font-family:
	&#34;Source Sans Pro&#34;,sans-serif"><a href="mailto:H
	adars@cynet.com"><span style="font-size:10.5pt;color:#1E2
	02C">Hadars@cynet.com</span></a> | <a href="htt
	ps://http://localhost:1333?u=N2UzODU4MjU4OTk4ZTg5MjAzMzUwNDQzMDk4YTBlZmVhMjM5MWVmZTI4ZGI0ZmMyOTQ4YmVkNTBhM2ZiMGE4MzRmODMwZDhlZTI3NGZmYzZkNDI4"><span style="font-size:10.5pt;color:
	#1E202C">www.cynet.com</span></a></span><o:p></o:p></p>
	
	</td>
	</tr>
	<tr>
	<td width="110" style="width:82.5pt;p
	adding:3.75pt .75pt .75pt .75pt">
	<p class="MsoNormal" s="" tyle="text-align:left;direction:ltr;unicode-bidi:embed">&lt;
	span style=&#34;font-size:13.5pt;font-family:-apple-system;co
	lor:black&#34;&gt;<img border="0" width="99" height="24" style="
	width:1.0312in;height:.25in" id="Picture_x0020_5" src="ci
	d:image006.png@01D9DFF7.3742A150" alt="Cynet logo"/><o:p></o:p></p>
	</td>
	<td style="border:none;border-le
	ft:solid #1E202C 1.0pt;padding:.75pt .75pt .75pt .75pt">
	
	<p class="MsoNormal" style="text-align:left;direction:lt
	r;unicode-bidi:embed"><span style="font-size:11.0pt"><img border="0" width="1" height="1" style="width:.0104in;hei
	ght:.0104in" id="Picture_x0020_6" src="cid:image005.png@0
	1D9DFF7.3742A150"/></span><o:p></o:p></p>
	</td>
	<td styl="" e="padding:.75pt .75pt .75pt .75pt">
	<p class="MsoNormal
	" style="text-align:left;direction:ltr;unicode-bidi:embed
	"><a href="http://localhost:1333?u=OWY2NWRkMzk2YjYxOGU0MDM5ZDFiMjRkNzVjOTVjODk1ZmY1NjRhMDkxYjJhNWEyNTc1YjYwZGZmMTFhOWE1NzAzYzAyMmUyODkxZDRlMDlmNDAwZDQ2MzA0YmJmNDQ3NTkzNzA1Y2I1MzRjN2M3MzM3MzQ3OGFiOTQwNzUzNDMzNzc4ZmYyYjBmMzJkNzkyNTk0Ng==
	175/"><span style="color:windowtext;text-decoration:none"><span style="font-size:13.5pt;font-family:-apple-system;
	color:blue"><img border="0" width="20" height="20" style="width:.2083in;height:.2083in" id="Picture_x0020_7" src="
	cid:image007.png@01D9DFF7.3742A150" alt="linkedin logo"/>&lt;
	/span&gt;</span></span></a><o:p></o:p></p>
	</td>
	<td style="paddi
	ng:.75pt .75pt .75pt .75pt"></td>
	<td style="padding:.75
	pt .75pt .75pt .75pt"></td>
	</tr>
	</tbody>
	</table>
	&lt;
	/td&gt;
	</td></tr>
	</tbody>
	</table>
	<p class="MsoNormal" sty="" le="text-align:left;direction:ltr;unicode-bidi:embed"><sp an="" lang="EN-US" style="font-size:11.0pt"> <o: p=""></o:></sp></p>
	<p class="MsoNormal" dir="RTL"><span lang="
	EN-US" dir="LTR" style="font-size:11.0pt;mso-ligatures:st
	andardcontextual"> </span><span dir="LTR"><o:p></o:p></span></p>
	</s></b></di></div><b><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt">
	</s></b></s></div><s pan="" style="font-size:11.0pt"><b><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt">
	</s></b></s></div><s pan="" style="font-size:11.0pt"><b><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt">
	</s></b></s></div><s pan="" style="font-size:11.0pt"><b><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt">
	</s></b></s></div><s pan="" style="font-size:11.0pt"><b><s pan="" lang="EN-US" dir="LTR" style="font-size:11.0pt">
	
	
	
	
	</s></b></s></body></html>